version: '3'

services:
  minecraft:
    image: lucasmarch/create_aab
    container_name: minecraft_server
    volumes:
      - server/
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
    restart: unless-stopped